// Major cities per country (alpha-2 code)
export const CITIES: Record<string, string[]> = {
  JP: ['Tokyo', 'Osaka', 'Kyoto', 'Hiroshima', 'Sapporo', 'Yokohama', 'Nara', 'Fukuoka', 'Nagoya', 'Okinawa', 'Hakone', 'Nikko'],
  FR: ['Paris', 'Lyon', 'Nice', 'Marseille', 'Bordeaux', 'Toulouse', 'Strasbourg', 'Mont Saint-Michel', 'Chamonix', 'Cannes', 'Avignon'],
  TH: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Koh Samui', 'Krabi', 'Ayutthaya', 'Chiang Rai', 'Hua Hin', 'Koh Phangan', 'Pai'],
  IT: ['Rome', 'Milan', 'Florence', 'Venice', 'Naples', 'Turin', 'Bologna', 'Amalfi', 'Positano', 'Cinque Terre', 'Siena', 'Capri', 'Sicily'],
  US: ['New York', 'Los Angeles', 'Chicago', 'San Francisco', 'Las Vegas', 'Miami', 'New Orleans', 'Seattle', 'Boston', 'Washington D.C.', 'Hawaii', 'Nashville', 'Austin', 'Denver', 'Portland'],
  ES: ['Madrid', 'Barcelona', 'Seville', 'Granada', 'Valencia', 'Bilbao', 'Toledo', 'Salamanca', 'San Sebastián', 'Ibiza', 'Mallorca', 'Tenerife'],
  KR: ['Seoul', 'Busan', 'Jeju', 'Incheon', 'Gyeongju', 'Jeonju', 'Daegu', 'Sokcho'],
  GR: ['Athens', 'Santorini', 'Mykonos', 'Rhodes', 'Crete', 'Corfu', 'Meteora', 'Thessaloniki', 'Zakynthos', 'Paros'],
  PT: ['Lisbon', 'Porto', 'Algarve', 'Sintra', 'Madeira', 'Azores', 'Évora', 'Cascais'],
  VN: ['Hanoi', 'Ho Chi Minh City', 'Hoi An', 'Da Nang', 'Ha Long Bay', 'Sapa', 'Nha Trang', 'Hue', 'Phu Quoc', 'Da Lat'],
  MX: ['Mexico City', 'Cancún', 'Tulum', 'Playa del Carmen', 'Oaxaca', 'Guadalajara', 'Los Cabos', 'Puerto Vallarta', 'Mérida', 'Guanajuato'],
  GB: ['London', 'Edinburgh', 'Manchester', 'Liverpool', 'Bath', 'Oxford', 'Cambridge', 'York', 'Bristol', 'Brighton', 'Cotswolds'],
  DE: ['Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Cologne', 'Heidelberg', 'Dresden', 'Nuremberg', 'Stuttgart', 'Rothenburg'],
  ID: ['Bali', 'Jakarta', 'Yogyakarta', 'Komodo', 'Lombok', 'Gili Islands', 'Ubud', 'Seminyak', 'Raja Ampat', 'Bunaken'],
  MA: ['Marrakech', 'Casablanca', 'Fes', 'Chefchaouen', 'Essaouira', 'Rabat', 'Sahara Desert', 'Tangier', 'Merzouga'],
  TR: ['Istanbul', 'Cappadocia', 'Ankara', 'Antalya', 'Bodrum', 'Pamukkale', 'Ephesus', 'Fethiye', 'Göreme'],
  NL: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Delft', 'Haarlem', 'Keukenhof', 'Maastricht'],
  CH: ['Zurich', 'Geneva', 'Bern', 'Lucerne', 'Interlaken', 'Zermatt', 'St. Moritz', 'Basel', 'Grindelwald'],
  AT: ['Vienna', 'Salzburg', 'Innsbruck', 'Hallstatt', 'Graz', 'Linz', 'Kitzbühel'],
  AU: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Cairns', 'Gold Coast', 'Byron Bay', 'Darwin', 'Uluru', 'Great Barrier Reef'],
  CN: ['Beijing', 'Shanghai', 'Guangzhou', 'Chengdu', "Xi'an", 'Hangzhou', 'Guilin', 'Lijiang', 'Zhangjiajie', 'Chongqing', 'Suzhou'],
  IN: ['Mumbai', 'Delhi', 'Jaipur', 'Agra', 'Goa', 'Kerala', 'Varanasi', 'Kolkata', 'Udaipur', 'Rishikesh', 'Darjeeling', 'Hampi'],
  SG: ['Singapore', 'Sentosa', 'Marina Bay'],
  MY: ['Kuala Lumpur', 'Penang', 'Langkawi', 'Kota Kinabalu', 'Melaka', 'Cameron Highlands', 'Tioman Island'],
  PH: ['Manila', 'Cebu', 'Boracay', 'Palawan', 'Siargao', 'Bohol', 'Coron', 'Davao'],
  NZ: ['Auckland', 'Wellington', 'Queenstown', 'Christchurch', 'Rotorua', 'Milford Sound', 'Franz Josef', 'Bay of Islands'],
  IS: ['Reykjavik', 'Akureyri', 'Blue Lagoon', 'Golden Circle', 'South Coast', 'Snæfellsnes', 'Westfjords'],
  PE: ['Lima', 'Cusco', 'Machu Picchu', 'Arequipa', 'Lake Titicaca', 'Sacred Valley', 'Iquitos', 'Paracas'],
  KE: ['Nairobi', 'Mombasa', 'Masai Mara', 'Amboseli', 'Diani', 'Samburu', 'Lamu'],
  JO: ['Amman', 'Petra', 'Wadi Rum', 'Dead Sea', 'Aqaba', 'Jerash'],
  NO: ['Oslo', 'Bergen', 'Tromsø', 'Flåm', 'Lofoten Islands', 'Stavanger', 'Geirangerfjord', 'Ålesund'],
  CA: ['Toronto', 'Vancouver', 'Montreal', 'Quebec City', 'Banff', 'Victoria', 'Whistler', 'Calgary', 'Ottawa'],
  BR: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Foz do Iguaçu', 'Florianópolis', 'Manaus', 'Natal', 'Recife', 'Fortaleza'],
  AR: ['Buenos Aires', 'Mendoza', 'Bariloche', 'Ushuaia', 'El Calafate', 'Salta', 'Córdoba'],
  ZA: ['Cape Town', 'Johannesburg', 'Durban', 'Kruger National Park', 'Garden Route', 'Stellenbosch', 'Knysna'],
  EG: ['Cairo', 'Luxor', 'Aswan', 'Hurghada', 'Sharm el-Sheikh', 'Alexandria', 'Dahab'],
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ras Al Khaimah'],
  NP: ['Kathmandu', 'Pokhara', 'Everest Base Camp', 'Chitwan', 'Annapurna', 'Lumbini', 'Bhaktapur'],
  LK: ['Colombo', 'Kandy', 'Galle', 'Sigiriya', 'Ella', 'Nuwara Eliya', 'Trincomalee'],
  TW: ['Taipei', 'Tainan', 'Kaohsiung', 'Taroko Gorge', 'Jiufen', 'Sun Moon Lake', 'Hualien'],
  MV: ['Malé', 'Maafushi', 'Baa Atoll', 'Ari Atoll', 'North Malé Atoll'],
  CZ: ['Prague', 'Brno', 'Český Krumlov', 'Karlovy Vary', 'Olomouc'],
  HU: ['Budapest', 'Eger', 'Pécs', 'Debrecen'],
  PL: ['Warsaw', 'Krakow', 'Gdańsk', 'Wrocław', 'Zakopane', 'Poznań'],
  HR: ['Dubrovnik', 'Split', 'Zagreb', 'Hvar', 'Plitvice Lakes', 'Rovinj', 'Korčula'],
  SI: ['Ljubljana', 'Lake Bled', 'Piran', 'Triglav'],
  BE: ['Brussels', 'Bruges', 'Ghent', 'Antwerp', 'Liège'],
  DK: ['Copenhagen', 'Aarhus', 'Odense'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Abisko', 'Kiruna', 'Visby'],
  FI: ['Helsinki', 'Rovaniemi', 'Turku', 'Lapland', 'Tampere'],
  IE: ['Dublin', 'Galway', 'Cork', 'Killarney', 'Cliffs of Moher', 'Connemara'],
  GE: ['Tbilisi', 'Batumi', 'Kazbegi', 'Kutaisi', 'Mestia'],
  UZ: ['Samarkand', 'Bukhara', 'Tashkent', 'Khiva', 'Nukus'],
  KH: ['Siem Reap', 'Phnom Penh', 'Sihanoukville', 'Battambang'],
  LA: ['Luang Prabang', 'Vientiane', 'Vang Vieng', '4000 Islands', 'Nong Khiaw'],
  MM: ['Yangon', 'Bagan', 'Mandalay', 'Inle Lake', 'Ngapali'],
  CO: ['Bogotá', 'Cartagena', 'Medellín', 'Santa Marta', 'Coffee Region', 'Cali'],
  CL: ['Santiago', 'Torres del Paine', 'Atacama', 'Valparaíso', 'Easter Island', 'San Pedro de Atacama'],
  CU: ['Havana', 'Varadero', 'Trinidad', 'Viñales', 'Cienfuegos'],
  TZ: ['Zanzibar', 'Serengeti', 'Arusha', 'Kilimanjaro', 'Dar es Salaam', 'Stone Town'],
  RU: ['Moscow', 'St. Petersburg', 'Lake Baikal', 'Sochi', 'Vladivostok', 'Kazan'],
  UA: ['Kyiv', 'Lviv', 'Odesa'],
  RS: ['Belgrade', 'Novi Sad', 'Niš'],
  ME: ['Kotor', 'Budva', 'Tivat', 'Perast', 'Ulcinj'],
  AL: ['Tirana', 'Gjirokastër', 'Berat', 'Sarandë'],
  MK: ['Skopje', 'Ohrid'],
  BA: ['Sarajevo', 'Mostar', 'Banja Luka'],
  NA: ['Windhoek', 'Etosha', 'Sossusvlei', 'Swakopmund'],
  BW: ['Maun', 'Okavango Delta', 'Chobe', 'Gaborone'],
  QA: ['Doha', 'Al Wakrah', 'Lusail'],
  SA: ['Riyadh', 'Jeddah', 'AlUla', 'Medina', 'NEOM'],
  IL: ['Jerusalem', 'Tel Aviv', 'Eilat', 'Haifa', 'Dead Sea'],
  AM: ['Yerevan', 'Lake Sevan', 'Tatev', 'Dilijan'],
  EC: ['Quito', 'Galápagos Islands', 'Cuenca', 'Baños', 'Amazon'],
  BO: ['La Paz', 'Salar de Uyuni', 'Sucre', 'Copacabana', 'Potosí'],
}
