export type Continent = 'Asia' | 'Europe' | 'Africa' | 'North America' | 'South America' | 'Oceania'

export interface Country {
  name: string      // user-facing display name
  geoName: string   // must match world-atlas properties.name exactly
  code: string      // ISO alpha-2 for flag emoji
  continent: Continent
}

/** Renders a country flag emoji from an ISO alpha-2 code */
export function flagEmoji(code: string): string {
  return [...code.toUpperCase()]
    .map(c => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65))
    .join('')
}

/** Formats a yyyy-mm-dd date string into a readable format */
export function fmtDate(iso: string | null): string {
  if (!iso) return ''
  return new Date(iso + 'T00:00:00').toLocaleDateString('en-US', {
    month: 'short', year: 'numeric',
  })
}

export const ALL_CONTINENTS: Continent[] = [
  'Asia', 'Europe', 'Africa', 'North America', 'South America', 'Oceania',
]

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan',           geoName: 'Afghanistan',                    code: 'AF', continent: 'Asia'          },
  { name: 'Albania',               geoName: 'Albania',                        code: 'AL', continent: 'Europe'        },
  { name: 'Algeria',               geoName: 'Algeria',                        code: 'DZ', continent: 'Africa'        },
  { name: 'Angola',                geoName: 'Angola',                         code: 'AO', continent: 'Africa'        },
  { name: 'Argentina',             geoName: 'Argentina',                      code: 'AR', continent: 'South America' },
  { name: 'Armenia',               geoName: 'Armenia',                        code: 'AM', continent: 'Asia'          },
  { name: 'Australia',             geoName: 'Australia',                      code: 'AU', continent: 'Oceania'       },
  { name: 'Austria',               geoName: 'Austria',                        code: 'AT', continent: 'Europe'        },
  { name: 'Azerbaijan',            geoName: 'Azerbaijan',                     code: 'AZ', continent: 'Asia'          },
  { name: 'Bangladesh',            geoName: 'Bangladesh',                     code: 'BD', continent: 'Asia'          },
  { name: 'Belarus',               geoName: 'Belarus',                        code: 'BY', continent: 'Europe'        },
  { name: 'Belgium',               geoName: 'Belgium',                        code: 'BE', continent: 'Europe'        },
  { name: 'Bolivia',               geoName: 'Bolivia',                        code: 'BO', continent: 'South America' },
  { name: 'Bosnia & Herzegovina',  geoName: 'Bosnia and Herzegovina',         code: 'BA', continent: 'Europe'        },
  { name: 'Brazil',                geoName: 'Brazil',                         code: 'BR', continent: 'South America' },
  { name: 'Bulgaria',              geoName: 'Bulgaria',                       code: 'BG', continent: 'Europe'        },
  { name: 'Cambodia',              geoName: 'Cambodia',                       code: 'KH', continent: 'Asia'          },
  { name: 'Cameroon',              geoName: 'Cameroon',                       code: 'CM', continent: 'Africa'        },
  { name: 'Canada',                geoName: 'Canada',                         code: 'CA', continent: 'North America' },
  { name: 'Chile',                 geoName: 'Chile',                          code: 'CL', continent: 'South America' },
  { name: 'China',                 geoName: 'China',                          code: 'CN', continent: 'Asia'          },
  { name: 'Colombia',              geoName: 'Colombia',                       code: 'CO', continent: 'South America' },
  { name: 'Costa Rica',            geoName: 'Costa Rica',                     code: 'CR', continent: 'North America' },
  { name: 'Croatia',               geoName: 'Croatia',                        code: 'HR', continent: 'Europe'        },
  { name: 'Cuba',                  geoName: 'Cuba',                           code: 'CU', continent: 'North America' },
  { name: 'Czech Republic',        geoName: 'Czech Republic',                 code: 'CZ', continent: 'Europe'        },
  { name: 'Denmark',               geoName: 'Denmark',                        code: 'DK', continent: 'Europe'        },
  { name: 'Dominican Republic',    geoName: 'Dominican Republic',             code: 'DO', continent: 'North America' },
  { name: 'Ecuador',               geoName: 'Ecuador',                        code: 'EC', continent: 'South America' },
  { name: 'Egypt',                 geoName: 'Egypt',                          code: 'EG', continent: 'Africa'        },
  { name: 'El Salvador',           geoName: 'El Salvador',                    code: 'SV', continent: 'North America' },
  { name: 'Estonia',               geoName: 'Estonia',                        code: 'EE', continent: 'Europe'        },
  { name: 'Ethiopia',              geoName: 'Ethiopia',                       code: 'ET', continent: 'Africa'        },
  { name: 'Finland',               geoName: 'Finland',                        code: 'FI', continent: 'Europe'        },
  { name: 'France',                geoName: 'France',                         code: 'FR', continent: 'Europe'        },
  { name: 'Georgia',               geoName: 'Georgia',                        code: 'GE', continent: 'Asia'          },
  { name: 'Germany',               geoName: 'Germany',                        code: 'DE', continent: 'Europe'        },
  { name: 'Ghana',                 geoName: 'Ghana',                          code: 'GH', continent: 'Africa'        },
  { name: 'Greece',                geoName: 'Greece',                         code: 'GR', continent: 'Europe'        },
  { name: 'Guatemala',             geoName: 'Guatemala',                      code: 'GT', continent: 'North America' },
  { name: 'Haiti',                 geoName: 'Haiti',                          code: 'HT', continent: 'North America' },
  { name: 'Honduras',              geoName: 'Honduras',                       code: 'HN', continent: 'North America' },
  { name: 'Hungary',               geoName: 'Hungary',                        code: 'HU', continent: 'Europe'        },
  { name: 'Iceland',               geoName: 'Iceland',                        code: 'IS', continent: 'Europe'        },
  { name: 'India',                 geoName: 'India',                          code: 'IN', continent: 'Asia'          },
  { name: 'Indonesia',             geoName: 'Indonesia',                      code: 'ID', continent: 'Asia'          },
  { name: 'Iran',                  geoName: 'Iran',                           code: 'IR', continent: 'Asia'          },
  { name: 'Iraq',                  geoName: 'Iraq',                           code: 'IQ', continent: 'Asia'          },
  { name: 'Ireland',               geoName: 'Ireland',                        code: 'IE', continent: 'Europe'        },
  { name: 'Israel',                geoName: 'Israel',                         code: 'IL', continent: 'Asia'          },
  { name: 'Italy',                 geoName: 'Italy',                          code: 'IT', continent: 'Europe'        },
  { name: 'Jamaica',               geoName: 'Jamaica',                        code: 'JM', continent: 'North America' },
  { name: 'Japan',                 geoName: 'Japan',                          code: 'JP', continent: 'Asia'          },
  { name: 'Jordan',                geoName: 'Jordan',                         code: 'JO', continent: 'Asia'          },
  { name: 'Kazakhstan',            geoName: 'Kazakhstan',                     code: 'KZ', continent: 'Asia'          },
  { name: 'Kenya',                 geoName: 'Kenya',                          code: 'KE', continent: 'Africa'        },
  { name: 'South Korea',           geoName: 'South Korea',                    code: 'KR', continent: 'Asia'          },
  { name: 'North Korea',           geoName: 'North Korea',                    code: 'KP', continent: 'Asia'          },
  { name: 'Kuwait',                geoName: 'Kuwait',                         code: 'KW', continent: 'Asia'          },
  { name: 'Laos',                  geoName: 'Laos',                           code: 'LA', continent: 'Asia'          },
  { name: 'Latvia',                geoName: 'Latvia',                         code: 'LV', continent: 'Europe'        },
  { name: 'Lebanon',               geoName: 'Lebanon',                        code: 'LB', continent: 'Asia'          },
  { name: 'Libya',                 geoName: 'Libya',                          code: 'LY', continent: 'Africa'        },
  { name: 'Lithuania',             geoName: 'Lithuania',                      code: 'LT', continent: 'Europe'        },
  { name: 'Malaysia',              geoName: 'Malaysia',                       code: 'MY', continent: 'Asia'          },
  { name: 'Mexico',                geoName: 'Mexico',                         code: 'MX', continent: 'North America' },
  { name: 'Moldova',               geoName: 'Moldova',                        code: 'MD', continent: 'Europe'        },
  { name: 'Mongolia',              geoName: 'Mongolia',                       code: 'MN', continent: 'Asia'          },
  { name: 'Morocco',               geoName: 'Morocco',                        code: 'MA', continent: 'Africa'        },
  { name: 'Mozambique',            geoName: 'Mozambique',                     code: 'MZ', continent: 'Africa'        },
  { name: 'Myanmar',               geoName: 'Myanmar',                        code: 'MM', continent: 'Asia'          },
  { name: 'Nepal',                 geoName: 'Nepal',                          code: 'NP', continent: 'Asia'          },
  { name: 'Netherlands',           geoName: 'Netherlands',                    code: 'NL', continent: 'Europe'        },
  { name: 'New Zealand',           geoName: 'New Zealand',                    code: 'NZ', continent: 'Oceania'       },
  { name: 'Nicaragua',             geoName: 'Nicaragua',                      code: 'NI', continent: 'North America' },
  { name: 'Nigeria',               geoName: 'Nigeria',                        code: 'NG', continent: 'Africa'        },
  { name: 'Norway',                geoName: 'Norway',                         code: 'NO', continent: 'Europe'        },
  { name: 'Oman',                  geoName: 'Oman',                           code: 'OM', continent: 'Asia'          },
  { name: 'Pakistan',              geoName: 'Pakistan',                       code: 'PK', continent: 'Asia'          },
  { name: 'Panama',                geoName: 'Panama',                         code: 'PA', continent: 'North America' },
  { name: 'Paraguay',              geoName: 'Paraguay',                       code: 'PY', continent: 'South America' },
  { name: 'Peru',                  geoName: 'Peru',                           code: 'PE', continent: 'South America' },
  { name: 'Philippines',           geoName: 'Philippines',                    code: 'PH', continent: 'Asia'          },
  { name: 'Poland',                geoName: 'Poland',                         code: 'PL', continent: 'Europe'        },
  { name: 'Portugal',              geoName: 'Portugal',                       code: 'PT', continent: 'Europe'        },
  { name: 'Qatar',                 geoName: 'Qatar',                          code: 'QA', continent: 'Asia'          },
  { name: 'Romania',               geoName: 'Romania',                        code: 'RO', continent: 'Europe'        },
  { name: 'Russia',                geoName: 'Russia',                         code: 'RU', continent: 'Europe'        },
  { name: 'Saudi Arabia',          geoName: 'Saudi Arabia',                   code: 'SA', continent: 'Asia'          },
  { name: 'Senegal',               geoName: 'Senegal',                        code: 'SN', continent: 'Africa'        },
  { name: 'Serbia',                geoName: 'Serbia',                         code: 'RS', continent: 'Europe'        },
  { name: 'Singapore',             geoName: 'Singapore',                      code: 'SG', continent: 'Asia'          },
  { name: 'Slovakia',              geoName: 'Slovakia',                       code: 'SK', continent: 'Europe'        },
  { name: 'Slovenia',              geoName: 'Slovenia',                       code: 'SI', continent: 'Europe'        },
  { name: 'Somalia',               geoName: 'Somalia',                        code: 'SO', continent: 'Africa'        },
  { name: 'South Africa',          geoName: 'South Africa',                   code: 'ZA', continent: 'Africa'        },
  { name: 'Spain',                 geoName: 'Spain',                          code: 'ES', continent: 'Europe'        },
  { name: 'Sri Lanka',             geoName: 'Sri Lanka',                      code: 'LK', continent: 'Asia'          },
  { name: 'Sudan',                 geoName: 'Sudan',                          code: 'SD', continent: 'Africa'        },
  { name: 'Sweden',                geoName: 'Sweden',                         code: 'SE', continent: 'Europe'        },
  { name: 'Switzerland',           geoName: 'Switzerland',                    code: 'CH', continent: 'Europe'        },
  { name: 'Syria',                 geoName: 'Syria',                          code: 'SY', continent: 'Asia'          },
  { name: 'Taiwan',                geoName: 'Taiwan',                         code: 'TW', continent: 'Asia'          },
  { name: 'Tanzania',              geoName: 'Tanzania',                       code: 'TZ', continent: 'Africa'        },
  { name: 'Thailand',              geoName: 'Thailand',                       code: 'TH', continent: 'Asia'          },
  { name: 'Tunisia',               geoName: 'Tunisia',                        code: 'TN', continent: 'Africa'        },
  { name: 'Turkey',                geoName: 'Turkey',                         code: 'TR', continent: 'Asia'          },
  { name: 'Uganda',                geoName: 'Uganda',                         code: 'UG', continent: 'Africa'        },
  { name: 'Ukraine',               geoName: 'Ukraine',                        code: 'UA', continent: 'Europe'        },
  { name: 'United Arab Emirates',  geoName: 'United Arab Emirates',           code: 'AE', continent: 'Asia'          },
  { name: 'United Kingdom',        geoName: 'United Kingdom',                 code: 'GB', continent: 'Europe'        },
  { name: 'United States',         geoName: 'United States of America',       code: 'US', continent: 'North America' },
  { name: 'Uruguay',               geoName: 'Uruguay',                        code: 'UY', continent: 'South America' },
  { name: 'Uzbekistan',            geoName: 'Uzbekistan',                     code: 'UZ', continent: 'Asia'          },
  { name: 'Venezuela',             geoName: 'Venezuela',                      code: 'VE', continent: 'South America' },
  { name: 'Vietnam',               geoName: 'Vietnam',                        code: 'VN', continent: 'Asia'          },
  { name: 'Yemen',                 geoName: 'Yemen',                          code: 'YE', continent: 'Asia'          },
  { name: 'Zambia',                geoName: 'Zambia',                         code: 'ZM', continent: 'Africa'        },
  { name: 'Zimbabwe',              geoName: 'Zimbabwe',                       code: 'ZW', continent: 'Africa'        },
]
